#! /bin/sh
# -*- sh -*-

file=~/media/pictures/Screenshots/Screenshot-$(date '+%Y%m%d%H%M%S').png
grim -g "$(slurp)" $file \
     && wl-copy $file \
	   && notify-send -i $file "File copied to clipboard"
