[Icon Theme]
Name = Old office
Name[de] = Altes Büro
Name[fr] = Vieux bureau
Comment[ru] = древний офис
Name[sp] = Antigua oficina
Comment = Steampunk theme around an old office.
Comment[de] = Thema von Steampunk um ein altes Büro.
Comment[fr] = Theme steampunk autour d'un vieux bureau.
Comment[ru] = Тема стимпанк вокруг древний офиса
Comment[sp] = Tema de Steampunk alrededor de una antigua oficina

